export const ATTENDANCE_DATA_ENTER_REQUEST = "ATTENDANCE_DATA_ENTER_REQUEST";
export const ATTENDANCE_DATA_ENTER_SUCCESS = "ATTENDANCE_DATA_ENTER_SUCCESS";
export const ATTENDANCE_DATA_ENTER_FAIL = "ATTENDANCE_DATA_ENTER_FAIL";
export const ATTENDANCE_DATA_ENTER_RESET = "ATTENDANCE_DATA_ENTER_RESET";

export const ATTENDANCE_ANALYSIS_REQUEST = "ATTENDANCE_ANALYSIS_REQUEST";
export const ATTENDANCE_ANALYSIS_SUCCESS = "ATTENDANCE_ANALYSIS_SUCCESS";
export const ATTENDANCE_ANALYSIS_FAIL = "ATTENDANCE_ANALYSIS_FAIL";
export const ATTENDANCE_ANALYSIS_RESET = "ATTENDANCE_ANALYSIS_RESET";

export const ATTENDANCE_DELETE_REQUEST = "ATTENDANCE_DELETE_REQUEST";
export const ATTENDANCE_DELETE_SUCCESS = "ATTENDANCE_DELETE_SUCCESS";
export const ATTENDANCE_DELETE_FAIL = "ATTENDANCE_DELETE_FAIL";
export const ATTENDANCE_DELETE_RESET = "ATTENDANCE_DELETE_RESET";